# https://circleci.com/docs/2.0/configuration-reference/
version: 2

# Workflow configuration
workflows:
  version: 2
  macos-build:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /.*-dev$/
                - /hotfix-.*/
# jobs
jobs:
  lint:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: update node and yarn
          command: |
            brew uninstall yarn
            brew uninstall node
            brew update
            brew upgrade
            brew cleanup
            brew install yarn
            yarn --version
            npm --version
            node --version
      - run:
          name: install dependencies
          command: |
            cp example.app-dev.json app-dev.json && cp example.app.json app.json
            yarn install
      - run:
          name: lint (standard)
          command: yarn run lint
  test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: update node and yarn
          command: |
            brew uninstall yarn
            brew uninstall node
            brew update
            brew upgrade
            brew cleanup
            brew install yarn
            yarn --version
            npm --version
            node --version
      - run:
          name: install dependencies
          command: |
            cp example.app-dev.json app-dev.json && cp example.app.json app.json
            yarn install
      - run:
          name: run mac tests
          command: yarn run test:ci-on-mac
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: update node and yarn
          command: |
            brew uninstall yarn
            brew uninstall node
            brew update
            brew upgrade
            brew cleanup
            brew install yarn
            yarn --version
            npm --version
            node --version
      - run:
          name: install dependencies
          command: |
            cp example.app-dev.json app-dev.json && cp example.app.json app.json
            yarn install
      - run:
          name: build
          command: yarn run build
